# Generated by Django 4.1.7 on 2023-04-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='last',
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
